CREATE TABLE IF NOT EXISTS TEAMS
(
 ID INTEGER AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(512) NOT NULL
);
-- STATEMENT MARKER
CREATE TABLE IF NOT EXISTS RESULTS
(
 ID INTEGER AUTO_INCREMENT PRIMARY KEY,
 TEAM_ID INTEGER NOT NULL CONSTRAINT RESULTS_TEAMS_ID_FK REFERENCES TEAMS,
 RESULT INTEGER NOT NULL,
 SCORE INTEGER NOT NULL
);
-- STATEMENT MARKER
CREATE INDEX IF NOT EXISTS results_teams_id_fk ON results (team_id);
